// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-3x7bC6XsiLvqtCvgDcldc_ljOrtH4ro',
    appId: '1:600039278458:web:caffe4e3ab6ba35610f8c3',
    messagingSenderId: '600039278458',
    projectId: 'teammate-3c11d',
    authDomain: 'teammate-3c11d.firebaseapp.com',
    storageBucket: 'teammate-3c11d.firebasestorage.app',
    measurementId: 'G-F6TSZMQDEX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRrxfjxh6DsNJzsJu6TejPvedVXmFvOK0',
    appId: '1:600039278458:android:4b0028b0a2c00c2810f8c3',
    messagingSenderId: '600039278458',
    projectId: 'teammate-3c11d',
    storageBucket: 'teammate-3c11d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDToURsXBesINyfa6NC2RHrWJ2NU48oEbA',
    appId: '1:600039278458:ios:7c8c446fe4dbd69c10f8c3',
    messagingSenderId: '600039278458',
    projectId: 'teammate-3c11d',
    storageBucket: 'teammate-3c11d.firebasestorage.app',
    iosClientId: '600039278458-0fi50d93hurac8mgcj2jmbno5tp19g1k.apps.googleusercontent.com',
    iosBundleId: 'com.example.teammate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDToURsXBesINyfa6NC2RHrWJ2NU48oEbA',
    appId: '1:600039278458:ios:7c8c446fe4dbd69c10f8c3',
    messagingSenderId: '600039278458',
    projectId: 'teammate-3c11d',
    storageBucket: 'teammate-3c11d.firebasestorage.app',
    iosClientId: '600039278458-0fi50d93hurac8mgcj2jmbno5tp19g1k.apps.googleusercontent.com',
    iosBundleId: 'com.example.teammate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-3x7bC6XsiLvqtCvgDcldc_ljOrtH4ro',
    appId: '1:600039278458:web:41f659061dc12b7110f8c3',
    messagingSenderId: '600039278458',
    projectId: 'teammate-3c11d',
    authDomain: 'teammate-3c11d.firebaseapp.com',
    storageBucket: 'teammate-3c11d.firebasestorage.app',
    measurementId: 'G-F0GJTST75H',
  );

}